### ISSUE TITLE
відповідь

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/pg-server#1]
https://github.com/VasylUlianovskyi/pg-server/blob/74e0508c1fa0fe62978ae383b9d0e86e5977cd97/controllers/phonesController.js#L8
- відповідь не містить створеної сутності. Варто перевірити, чи вона успішно створюється в базі і чи прокидається з моделі в контролер

**Comment by VasylUlianovskyi** [comment]
++
