### ISSUE TITLE
іменування

### ISSUE THREAD

**Issue by pecourses** [VasylUlianovskyi/pg-server#2]
https://github.com/VasylUlianovskyi/pg-server/blob/74e0508c1fa0fe62978ae383b9d0e86e5977cd97/controllers/phonesController.js#L7
https://github.com/VasylUlianovskyi/pg-server/blob/74e0508c1fa0fe62978ae383b9d0e86e5977cd97/models/phone.js#L18
- `createPhone` містить дієслово в наказовому способі ("_створи телефон_"), це більше схоже на назву функції. Якщо це змінна з даними, то краще використовувати пасивну форму `createdPhone` ("_створений телефон_")

**Comment by VasylUlianovskyi** [comment]
++

**Comment by VasylUlianovskyi** [comment]
++
